# Generated by Django 6.0 on 2025-12-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credit_score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'customer_table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='customer_ta_email_6bdef5_idx')],
                'unique_together': {('first_name', 'last_name', 'address')},
            },
        ),
    ]
