# Generated by Django 6.0 on 2025-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customers', models.ManyToManyField(blank=True, related_name='partners', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Partner',
                'db_table': 'partner_table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='partner_tab_created_53cc6e_idx')],
                'unique_together': {('company_name', 'address')},
            },
        ),
    ]
