# Generated by Django 6.0 on 2025-12-14 19:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('annual_rate', models.DecimalField(decimal_places=2, default=20, max_digits=4)),
                ('term_months', models.IntegerField(default=12, null=True)),
                ('issue_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'db_table': 'loan_table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='loan_table_custome_142fc1_idx')],
                'unique_together': {('customer', 'loan_amount', 'annual_rate', 'term_months')},
            },
        ),
    ]
